nombre = input("Cual es tu nombre? ")
apellido = input("Cual es tu apellido? ")
Code = input("Cual es el codigo de tu seccion? ")
CD = input("Cual es tu sede? ")
print("Hola " + nombre + " " + apellido + " seccion " + Code + " Sede " + CD)